######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : blackdiamond, Index = 0, Count = 1
# SUBMIT FILE NAME : preprocess_j1.sub
######################################################################
stream_error  = false
stream_output = false
environment = "CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=dc74a7ad-7076-4ac5-8b4a-b37d1ee1647a PEGASUS_WF_LABEL=blackdiamond PEGASUS_DAG_JOB_ID=preprocess_j1 PEGASUS_SITE=local _PEGASUS_TRANSFER_INPUT_FILES=/home/dbrown/projects/osg/condor-blackdiamond-container/dags/dbrown/pegasus/blackdiamond/run0003/./stage_in_remote_local_0_0.meta,/usr/share/pegasus/sh/pegasus-lite-common.sh,/home/dbrown/projects/osg/condor-blackdiamond-container/dags/dbrown/pegasus/blackdiamond/run0003/pegasus-worker-4.9.0dev-x86_64_rhel_7.tar.gz, PEGASUS_BIN_DIR=/usr/bin"
arguments = "/home/dbrown/projects/osg/condor-blackdiamond-container/dags/dbrown/pegasus/blackdiamond/run0003/./preprocess_j1.sh "
copy_to_spool = false
error = /home/dbrown/projects/osg/condor-blackdiamond-container/dags/dbrown/pegasus/blackdiamond/run0003//./preprocess_j1.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
getenv = True
log = /home/dbrown/projects/osg/condor-blackdiamond-container/dags/dbrown/pegasus/blackdiamond/run0003/blackdiamond-0.log
notification = NEVER
output = /home/dbrown/projects/osg/condor-blackdiamond-container/dags/dbrown/pegasus/blackdiamond/run0003//./preprocess_j1.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 43200)
priority = 20
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
use_x509userproxy = True
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "dc74a7ad-7076-4ac5-8b4a-b37d1ee1647a"
+pegasus_wf_uuid = "dc74a7ad-7076-4ac5-8b4a-b37d1ee1647a"
+pegasus_version = "4.9.0dev"
+pegasus_wf_name = "blackdiamond-0"
+pegasus_wf_app = "ligo-pycbc"
+pegasus_wf_time = "20181023T172515-0400"
+pegasus_wf_xformation = "pegasus::preprocess:4.0"
+pegasus_wf_dax_job_id = "j1"
+pegasus_wf_dag_job_id = "preprocess_j1"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
